version: "3.8"

services:

  web:

    image: shinjwde/duckmealng:latest

    network_mode: host

    restart: on-failure

    environment:
      - SPRING_DATA_MONGODB_HOST=localhost

      - SPRING_DATA_REDIS_HOST=localhost

      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - MONGO_USERNAME=${MONGO_USERNAME}

      - MONGO_PASSWORD=${MONGO_PASSWORD}

    depends_on:

      - mongo

      - redis

  mongo:

    image: shinjwde/duckmealng-mongo:latest

    ports:

      - "27017:27017"

    volumes:

      - mongo-data:/data/db

    environment:

      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}

      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

    restart: on-failure

  redis:

    image: shinjwde/duckmealng-redis:latest

    ports:

      - "6379:6379"

    environment:

      - REDIS_PASSWORD=${REDIS_PASSWORD}

    command: redis-server --requirepass ${REDIS_PASSWORD}

    restart: on-failure

volumes:

  mongo-data:


