version: "3.8"

services:
  web:
    image: shinjwde/duckmealng:latest
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - redis_password
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mongo
      - redis

  mongo:
    image: shinjwde/duckmealng-mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: shinjwde/duckmealng-redis:latest
    ports:
      - "6379:6379"
    secrets:
      - redis_password
    command: [ "redis-server", "--requirepass", "/run/secrets/redis_password" ]
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  mongo-data:

secrets:
  redis_password:
    external: true
