services:
  web:
    image: shinjwde/duckmealng:latest
    container_name: duckmealng-web
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    restart: unless-stopped


  mongo:
    image: shinjwde/duckmealng-mongo:latest
    container_name: duckmealng-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: shinjwde/duckmealng-redis:latest
    container_name: duckmealng-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    secrets:
      - redis_password
    command: >
      sh -c "redis-server --requirepass $(cat /run/secrets/redis_password)"

volumes:
  mongo-data:


secrets:
  redis_password:
    external: true