spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  logging:
    level:
      org:
        springframework:
          web: DEBUG
      root: DEBUG

jwt:
  secret-key: "duckmelangduckmelangduckmelangduckmelangduckmelang"
  access-expiration: 3600000     # 1시간
  refresh-expiration: 604800000  # 7일
