apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: duckmelang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: duckmelang-app-nodes
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672   # AMQP
            - containerPort: 15672  # 관리 UI
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: duckmelang
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672